//Constants for user
export const GET_USER_FIRST_NAME = "GET_USER_FIRST_NAME";
export const GET_USER_LAST_NAME = "GET_USER_LAST_NAME";
export const GET_USER_EMAIL = "GET_USER_EMAIL";
export const GET_USER_PASSWORD = "GET_USER_PASSWORD";

export const CHECK_USER_PENDING = "CHECK_USER_PENDING";
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
export const CHECK_USER_FAILED = "CHECK_USER_FAILED";

export const ADDING_USER_PENDING = "ADDING_USER_PENDING";
export const ADDING_USER_SUCCESS = "ADDING_USER_SUCCESS";
export const ADDING_USER_FAILED = "ADDING_USER_FAILED";

//Constants for Blog
export const GET_BLOG_HEADING = "GET_BLOG_HEADING";
export const GET_BLOG_CONTENT = "GET_BLOG_CONTENT";
export const GET_BLOG_AUTHOR = "GET_BLOG_AUTHOR";
export const ADD_BLOG_ITEM = "ADD_BLOG_ITEM";
export const BLOG_SELECTED = "BLOG_SELECTED";


export const GETTING_BLOG_PENDING = "GETTING_BLOG_PENDING";
export const GETTING_BLOG_SUCCESS = "GETTING_BLOG_SUCCESS";
export const GETTING_BLOG_FAILED = "GETTING_BLOG_FAILED";

export const ADDING_BLOG_PENDING = "ADDING_BLOG_PENDING";
export const ADDING_BLOG_SUCCESS = "ADDING_BLOG_SUCCESS";
export const ADDING_BLOG_FAILED = "ADDING_BLOG_FAILED";

export const GETTING_BLOGPOST_PENDING = "GETTING_BLOGPOST_PENDING";
export const GETTING_BLOGPOST_SUCCESS = "GETTING_BLOGPOST_SUCCESS";
export const GETTING_BLOGPOST_FAILED = "GETTING_BLOGPOST_FAILED";

export const GET_COMMENT_HEADING = "GET_COMMENT_HEADING";
export const GET_COMMENTATOR = "GET_COMMENTATOR";
export const GET_COMMENT_BODY = "GET_COMMENT_BODY";
export const ADD_COMMENT = "ADD_COMMENT";

export const ADDING_COMMENT_PENDING = "ADDING_COMMENT_PENDING";
export const ADDING_COMMENT_SUCCESS = "ADDING_COMMENT_SUCCESS";
export const ADDING_COMMENT_FAILED = "ADDING_COMMENT_FAILED";